[package]
name = "cardor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
kurbo = "0.10.4"
native-dialog = "0.7.0"
